# Generated by Django 3.1.7 on 2021-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincycle',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
