# Generated by Django 3.1.7 on 2021-05-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_maincycle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='boost_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maincycle',
            name='auto_click_power',
            field=models.IntegerField(default=0),
        ),
    ]
